# The URL the site will be built for
base_url = "https://mxdzs0612.github.io/"
title = "mxdzs0612的博客"
description = "尝试重启博客中,当成笔记软件用的，无所谓有没有人看了～"
taxonomies = [{name = "tags", feed = true}]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feeds = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

default_language = "zh-Hans"

theme = "tabi"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
external_links_class = "external"

[extra]
# Put all your custom variables here
default_mode = "dark"
# Enable JavaScript theme toggler to allow users to switch between dark/light mode.
# If disabled, your site will use the theme specified in the `default_theme` variable.
theme_switcher = true
# Add a "copy" button to code blocks (loads ~700 bytes of JavaScript).
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy
copy_button = true
# Make code block names clickable if they are URLs (loads ~400 bytes of JavaScript).
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy
code_block_name_links = false
# Quick navigation buttons.
# Adds "go up" and "go to comments" buttons on the bottom right (hidden for mobile).
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy
quick_navigation_buttons = true

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
    { name = "github", url = "https://github.com/mxdzs0612", trailing_slash = false },
]

[extra.comment.utterances]
repo = "mxdzs0612/mxdzs0612.github.io"
issue_term = "pathname"
theme = "github-dark"
